name: Build All Basic Images

on:
  workflow_dispatch:

concurrency:
  group: build-basic-images
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    strategy:
      matrix:
        app:
          - base
          - base-debian
          - base-alpine
    uses: ./.github/workflows/reusable-build-image.yml
    with:
      app: ${{ matrix.app }}
    secrets: inherit
