name: Build Single App Image

on:
  workflow_dispatch:
    inputs:
      app:
        description: "Which app to build"
        required: true
        type: choice
        default: me
        options:
          - base
          - base-debian
          - base-alpine
          - me

concurrency:
  group: build-app-images
  cancel-in-progress: true

jobs:
  build-and-push:
    uses: ./.github/workflows/reusable-build-image.yml
    with:
      app: ${{ inputs.app }}
    secrets: inherit
